@apimEndpoint = {{$dotenv APIM_SERVICE_ENDPOINT}}
@typeJson = Accept: application/json

@access-token = <Your Access token here>

###
# @name = Get Products from APIM Endpoint
GET {{apimEndpoint}}/ask
{{typeJson}}
Authorization: Bearer {{access-token}}
