@apimEndpoint = {{$dotenv APIM_SERVICE_ENDPOINT}}
@typeJson = Accept: application/json

@access-token = <Your Access token here>

POST {{apimEndpoint}}/ask
Content-Type: application/json
{{typeJson}}
Authorization: Bearer {{access-token}}

{
  "query": "I want shoes with city lifestyle design, what do you suggest?"
}
