@apimEndpoint = {{$dotenv APIM_SERVICE_ENDPOINT}}
@products = products
@typeJson = Accept: application/json

@access-token = <Your Access token here>

###
GET {{apimEndpoint}}/{{products}}
{{typeJson}}
Authorization: Bearer {{access-token}}
