@apimEndpoint = {{$dotenv APIM_SERVICE_ENDPOINT}}
@products = products
@id = <Your Product ID here>
@typeJson = Accept: application/json

@access-token = <Your Access token here>

###
# @name = Get Products from APIM Endpoint
GET {{apimEndpoint}}/{{products}}/{{id}}
{{typeJson}}
Authorization: Bearer {{access-token}}
