@apimEndpoint = {{$dotenv APIM_SERVICE_ENDPOINT}}
@products = products
@typeJson = Accept: application/json

###
# @name = Get Products from APIM Endpoint
GET {{apimEndpoint}}/{{products}}
{{typeJson}}
