@apimEndpoint = {{$dotenv APIM_SERVICE_ENDPOINT}}
@typeJson = Accept: application/json

@access-token = <Your Access token here>

###
POST {{apimEndpoint}}/vectorize
{{typeJson}}
Authorization: Bearer {{access-token}}
